### ISSUE TITLE
Openhab3 "not authorized"

### ISSUE THREAD

**Issue by tlrider99** [SEPIA-Framework/sepia-docs#143]
Hi Florian,

I hope you are doing well.
Short question, I can't connect to my openhab installation. I encode my "user:password" and set the authentication to "Basic" like issu113, but it doesn't work for me. Do you have any idea?

Grüße
Dirk

**Comment by fquirin** [comment]
Hi Dirk (@tlrider99),

doing well, hope you're well too :-). Don't be confused but I moved your issue to this repository to keep all questions in one place ;-).

Do you get any error messages? Something ins the Assist-Server logs (sepia-assist-server/log.out)?
First we should find out if your password gets rejected or the connection itself.

**Comment by tlrider99** [comment]
Hi Florian,

thanks I'm fine too. The error message is ""result": "fail",   "error": "no devices found or failed to contact HUB"" .  I could not find anything in the log either. I attached the log.out.


[log.out.txt](https://github.com/SEPIA-Framework/sepia-docs/files/7739255/log.out.txt)
![image](https://user-images.githubusercontent.com/29237172/146641949-a2d75f1a-b93b-48e4-972d-de83ae534bcc.png)

**Comment by fquirin** [comment]
Hi Dirk,

I'm seeing a lot of requests using the admin account 'uid1003'. This account is not meant to be used as actual "user" and you can get in trouble doing this for different reasons :sweat_smile: (security, user experience, actual service errors).

Can you please [create a new user](https://github.com/SEPIA-Framework/sepia-docs/wiki/Create-and-Edit-Users#create-new-user) with all the smarthome rules first and try again?

**Comment by tlrider99** [comment]
Hi Florian,
I created a new user with smarthome rights. After loading hub infos I see the green connection light but after discovery the e.g. lights the connection light is switch to red.

![image](https://user-images.githubusercontent.com/29237172/146643795-7b337dc5-9d9c-43fa-b038-c1bbf44f4a7e.png)

![image](https://user-images.githubusercontent.com/29237172/146643750-728ad837-2f10-495d-b308-15afee134ca0.png)

example for an openhab item:
Dimmer Licht_Buero                   "Büro Decke"    (Licht) ["Licht", "Light"] { channel="knx:device:bridge:AKD_0401_1:Channel_D" }
Thanks for your patience

**Comment by fquirin** [comment]
Ok, user setup looks good now :-).
The light will be green when the configuration of SEPIA has been loaded. Unfortunately that doesn't mean the connection to the HUB actually works since this is evaluated during "get devices".

I think we should try and see if the server can actually access OpenHAB.
Can you login to your SEPIA-Home device and run `ping4 192.168.10.90` please?
If that works I can lookup the authenticated CURL request to see if we can use Basic Auth. to access OpenHAB.

Btw, do you actually use Basic Auth. or OAuth? It looks like OpenHAB 3 has more options now:
https://www.openhab.org/docs/configuration/restdocs.html

**Comment by tlrider99** [comment]
Hi Florian, 
I hope you are doing well.
Now a year has passed and I have seen that you have tried to solve the problem in different issues. Have you found a solution?

2022-12-19 18:41:26 ERROR - Service:OpenHAB - failed to get devices from server!

This is the error I get, whether with Basic Authentication or with Bearer/Token.

Do you have another idea? I would like to work on the language control again between the holidays.

Have fun
Dirk

**Comment by fquirin** [comment]
Hi Dirk,

catched a cold, but everything ok so far. Hope you're doing better? ^^.

> Have you found a solution?

Hard to say, since we never really found out what the issue was in your setup :-/. I did fix some minor bugs, but nothing that could have prevented authorization, I think. I might have improved the log, but I can't remember exactly 😅.

We should probably continue where we let off the last time. First I'd suggest to do an update to the most recent version if you haven't already, then check what happens and if anything pops up in the server log (SEPIA/sepia-assist-server/log.out).
After that I'd try this step again: `Can you login to your SEPIA-Home device and run ping4 192.168.10.90 please?`

**Comment by vanseforge** [comment]
I also get the error message
```
{
  "result": "fail",
  "error": "failed to load data from HUB"
}
```
I installed SEPIA Home via docker on my Synology DS920+ and want to connect to OpenHAB 3.4. I created a OpenHAB token and entered it in the SEPIA settings. If I select something under GET DEVICES I get the above error message and this:
![grafik](https://user-images.githubusercontent.com/59662590/208730587-4442c673-eac9-4799-ab1c-3287e116a0fe.png)

**Comment by fquirin** [comment]
@tlrider99 , @vanseforge could you both please open a terminal on your SEPIA server machine and try to contact your openHAB server from there like this:

```
curl -X GET 'http://[openHAB-IP]:8080/rest/items'
```

And if you get "not authorized" error please try:

```
curl -H 'Authorization: Bearer [my-token]' -X GET 'http://[openHAB-IP]:8080/rest/items'
```

**Comment by vanseforge** [comment]
I tried your curl command (without token) on my docker host and from a bash in the docker container. Both times a get a json list with the items.

**Comment by fquirin** [comment]
ok, thats good.

Looking at your screenshot again I just realized that there is no protocol given for the URL.
Please make sure you have something like `http://10.0.0.3:8080` instead of only the IP!

If you go to 'Core settings' page in your SEPIA Control-HUB and load the persistence settings you should see something like this (instead of 'localhost' your '10.0.0.3' IP):

![image](https://user-images.githubusercontent.com/18550513/209208104-1badf286-0450-4261-93e7-8326ef39f3e8.png)

The field 'smarthome_hub_auth_data' usually says '[HIDDEN]' I just copied the token again to demonstrate the right format.

**Comment by vanseforge** [comment]
🫣
I am sorry. I thought I already tried it with the http.. of course it is working now.
Danke.

**Comment by fquirin** [comment]
np, at least this one was easy to fix ^^

**Comment by tlrider99** [comment]
Hi Florian,
 
sorry I saw your message only now. I'll do it today evening and give you feedback.

Regards
Dirk

**Comment by tlrider99** [comment]
Hi Florian,

here are the results:
ping4 192.168.10.90
PING 192.168.10.90 (192.168.10.90) 56(84) bytes of data.
64 bytes from 192.168.10.90: icmp_seq=1 ttl=64 time=0.407 ms
64 bytes from 192.168.10.90: icmp_seq=2 ttl=64 time=0.258 ms
64 bytes from 192.168.10.90: icmp_seq=3 ttl=64 time=0.243 ms

curl -X GET 'http://192.168.10.90:8080/rest/items'
http://192.168.10                                                                 .90:8080/rest/items/Steckdosen_aussen","state":"NULL","editable":true,"type":"Gr                                                                                    oup","name":"Steckdosen_aussen","label":"Steckdosen","category":"poweroutlet_eu"                                                                                    ,"tags":["Equipment"],"groupNames":["Terrasse"]},{"link":"http://192.168.10.90:8                                                                                    080/rest/items/MycroftKuche_ListenState","state":"OFF","editable":true,"type":"S                                                                                    witch","name":"MycroftKuche_ListenState","label":"Listen State","category":"","t                                                                                    ags":["Point"],"groupNames":["Mycroft_Kueche"]},{"link":"http://192.168.10.90:80                                                                                    80/rest/items/VorratskellerTemperatureHumiditySensor_Temperature","state":"20.21                                                                                     °C","stateDescription":{"pattern":"%.1f %unit%","readOnly":true,"options":[]},"                                                                                    editable":true,"type":"Number:Temperature","name":"VorratskellerTemperatureHumid                                                                                    itySensor_Temperature","label":"Temperature Vorratskeller","category":"Temperatu                                                                                    re","tags":["Point"],"groupNames":["VorratskellerTemperatureHumiditySensor"]}]

curl seems to work.

Regards
Dirk

**Comment by fquirin** [comment]
Hi Dirk,

so this curl request was done from the same machine your SEPIA server is running on right?
Can you double-check your 'Core settings' page please and try the `Bearer` auth. mode with openHAB API token once more? (don't forget to reload the server).
If that still doesn't work can you check the `[SEPIA]/sepia-assist-server/log.out` file again after you pressed "get devices" in the Control-HUB.

**Comment by tlrider99** [comment]
Hi Florian,
I stored a new token and reload the server with the same result. 
2022-12-29 16:38:48 ERROR - OpenHAB - failed to get devices from server!

Yes, I made the curl query from the Raspi on which the Sepia server is running. That also works.

Here with bearer and token:
 curl -H "Authorization: Bearer oh.sepia.slOMPy2LjJwpmmSgDTYtmlnrkamlIpSxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"A -X GET http://192.168.10.90:8080/rest/items
[{"link":"http://192.168.10.90:8080/rest/items/Schaltaktor2_Steckdose18Mikrowelle","state":"ON","editable":true,"type":"Switch","name":"Schaltaktor2_Steckdose18Mikrowelle","label":" Mikrowelle","category":"switch","tags":["Point"],"groupNames":["Kuechengeraete_Steckdosen"]},{"link":"http://192.168.10.90:8080/rest/items/LocalWeatherandForecast_ForecastDay3_Winddirection","state":"189 °","stateDescription":{"pattern":"%.1f %unit%","readOnly":true,"options":[]},"editable":true,"type":"Number:Angle","name":"LocalWeatherandForecast_ForecastDay3_Winddirection","label":"Vorhergesagte Windrichtung in 3 Tagen","category":"Wind","tags":["Point"],"groupNames":["LocalWeatherandForecast"]},{"members":[],"link":"http://192.168.10.90:8080/rest/items/Lueftung_Finni","state":"NULL","editable":true,"type":"Group","name":"Lueftung_Finni","label":"Lüftung Finnian","category":"fan","tags":["Equipment"],"groupNames":["Finnian"]},{"link":"http://192.168.10.90:8080/rest/items/UnsereFee_ControlFanLevel","state":"100","stateDescription":{"minimum":-1,"maximum":105,"step":1,"pattern":"%.0f","readOnly":false,"options":[{"value":"38","label":"Silent"},{"value":"60","label":"Standard"},{"value":"75","label":"Turbo"},{"value":"77","label":"Power"},{"value":"90","label":"Full"},{"value":"100","label":"Max"},{"value":"101","label":"Quiet"},{"value":"102","label":"Balanced"},{"value":"103","label":"Turbov2"},{"value":"104","label":"Maxv2"},{"value":"105","label":"Mob"},{"value":"-1","label":"Custom"}]},"commandDescription":{"commandOptions":[{"command":"38","label":"Silent"},{"command":"60","label":"Standard"},{"command":"75","label":"Turbo"},{"command":"77","label":"Power"},{"command":"90","label":"Full"},{"command":"100","label":"Max"},{"command":"101","label":"Quiet"},{"command":"102","label":"Balanced"},{"command":"103","label":"Turbov2"},{"command":"104","label":"Maxv2"},{"command":"105","label":"Mob"},{"command":"-1","label":"Custom"}]},"editable":true,"type":"Number","name":"UnsereFee_ControlFanLevel","label":"Control Fan Level","category":"","tags":["Point"],"groupNames":["UnsereFee"]},{"link":"http://192.168.10.90:8080/rest/items/HeizungsaktorOG_SollwertaktuellKinderzimmerSued","state":"21.0","stateDescription":{"pattern":"%.0f","readOnly":false,"options":[]},"editable":true,"type":"Number","name":"HeizungsaktorOG_SollwertaktuellKinderzimmerSued","label":"Sollwert aktuell ","category":"temperature","tags":["Point"],"groupNames":["Heizung_Mattis"]},{"link":"http://192.168.10.90:8080/rest/items/Papiertonne_Ergebnisstart","state":"2023-01-17T00:00:00.000+0100","stateDescription":{"pattern":"%1$td.%1$tm.%1$tY","readOnly":true,"options":[]},"editable":true,"type":"DateTime","name":"Papiertonne_Ergebnisstart","label":"Ergebnisstart","category":"","tags":["sepia-name\u003dPapiertonne","sepia-type\u003dother","sepia-room\u003dgarage","Point"],"groupNames":["Papiertonne"]},{"link":"http://192.168.10.90:8080/rest/items/CVLAN_BenutzerID","state":"5","transformedState":"Finnian","stateDescription":{"pattern":"MAP(ekey_nutzer.map):%s","readOnly":true,"options":[]},"editable":true,"type":"Number","name":"CVLAN_BenutzerID","label":"ekey Benutzer ID","category":"","tags":["Point"],"groupNames":["ekey"]},{"link":"http://192.168.10.90:8080/rest/items/XiaomiMiTemperatureHumidityBuero_Temperature","state":"22.3 °C","stateDescription":{"pattern":"%.1f %unit%","readOnly":true,"options":[]},"editable":true,"type":"Number:Temperature","name":"XiaomiMiTemperatureHumidityBuero_Temperature","label":"Temperature Büro","category":"Temperature","tags":["Point"],"groupNames":["XiaomiMiTemperatureHumidityBuero"]},{"link":"http://192.168.10.90:8080/rest/items/MycroftKuche_VolumeDuck","state":"OFF","editable":true,"type":"Switch","name":"MycroftKuche_VolumeDuck","label":"Volume Duck","category":"","tags":["Point"],"groupNames":["Mycroft_Kueche"]},{"link":"http://192.168.10.90:8080/rest/items/Dimmaktor2_FlurEG","state":"40","editable":true,"type":"Dimmer","name":"Dimmaktor2_FlurEG","label":"Licht Flur EG","category":"lightbulb","tags":["Light","Point"],"groupNames":["Licht_Flur_EG"]},{"link":"http://192.168.10.90:8080/rest/items/HeizungsaktorEG_SollwertBuero","state":"21 °C","stateDescription":{"pattern":"%.0f","readOnly":false,"options":[]},"editable":true,"type":"Number:Temperature","name":"HeizungsaktorEG_SollwertBuero","label":"Sollwert Büro","category":"temperature","tags":["Point"],"groupNames":["Heizung_Buero"]},{"link":"http://192.168.10.90:8080/rest/items/LocalWeatherandForecast_ForecastHours09_Maxtemperature","state":"7.18 °C","stateDescription":{"pattern":"%.1f %unit%","readOnly":true,"options":[]},"editable":true,"type":"Number:Temperature","name":"LocalWeatherandForecast_ForecastHours09_Maxtemperature","label":"Maximale Temperatur 9h","category":"Temperature","tags":["Point"],"groupNames":["LocalWeatherandForecast"]},{"link":"http://192.168.10.90:8080/rest/items/LocalWeatherandForecast_ForecastDay3_Pressure","state":"1023 hPa","stateDescription":{"pattern":"%.3f %unit%","readOnly":true,"options":[]},"editable":true,"type":"Number:Pressure","name":"LocalWeatherandForecast_ForecastDay3_Pressure","label":"Vorhergesagter Luftdruck in 3 Tagen","category":"Pressure","tags":["Point"],"gr

Grüßle
Dirk

**Comment by fquirin** [comment]
Ok that's really weird :-/.

I've added some debug info to the output. Could you stop the server, then replace the jar `[SEPIA]/sepia-assist-server/sepia-assist-v2.7.0.jar` with the one from this ZIP file: [sepia-assist-v2.7.0.zip](https://github.com/SEPIA-Framework/sepia-docs/files/10321827/sepia-assist-v2.7.0.zip) and restart?
Then try again and check the log to see what appears after `OpenHAB - failed to get devices from server!`.

**Comment by tlrider99** [comment]
Hi Florian,
 I did it, but the server seems not to start. This is the output from log.out
     ___    ___   ___   ___   ___       
     |___   |___  |___]   |   |___|      
     ____|. |___. |    . _|_. |   |.     
                                         
    https://sepia-framework.github.io    
                                         
2022-12-31 13:07:27 LOG - Security policy and manager set.
2022-12-31 13:07:27 LOG - Security sandbox loaded with 6 entries.
2022-12-31 13:07:27 LOG - JAVA_HOME: /usr/lib/jvm/java-11-openjdk-armhf
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/JsonFactory
	at net.b07z.sepia.server.core.tools.PropertiesReader.loadFile(PropertiesReader.java:42)
	at net.b07z.sepia.server.assist.server.Config.loadSettings(Config.java:499)
	at net.b07z.sepia.server.assist.server.Start.loadConfigFile(Start.java:88)
	at net.b07z.sepia.server.assist.server.Start.loadSettings(Start.java:153)
	at net.b07z.sepia.server.assist.server.Start.main(Start.java:395)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more

**Comment by fquirin** [comment]
Ah crap, it looks like some dependencies have changed since the last build :-| Can you copy the jar files from this ZIP to the `libs` folder next to the `[SEPIA]/sepia-assist-server/sepia-assist-v2.7.0.jar` plz: 
[libs.zip](https://github.com/SEPIA-Framework/sepia-docs/files/10327375/libs.zip)

I hope these are all changes 🤞

**Comment by tlrider99** [comment]
log.out
-----------------------------------------
      ___    ___   ___   ___   ___       
     |___   |___  |___]   |   |___|      
     ____|. |___. |    . _|_. |   |.     
                                         
    https://sepia-framework.github.io    
                                         
2022-12-31 16:35:17 LOG - Security policy and manager set.
2022-12-31 16:35:17 LOG - Security sandbox loaded with 6 entries.
2022-12-31 16:35:17 LOG - JAVA_HOME: /usr/lib/jvm/java-11-openjdk-armhf
2022-12-31 16:35:18 LOG - Loading settings from Xtensions/assist.custom.properties... done.
2022-12-31 16:35:18 LOG - --- Running SEPIA-Assist-API with CUSTOM settings ---
2022-12-31 16:35:18 [main] INFO StaticFilesConfiguration - External StaticResourceHandler configured with folder = Xtensions/WebContent
2022-12-31 16:35:18 LOG - Web-server is active and uses folder: Xtensions/WebContent - CORS (files): *
2022-12-31 16:35:18 LOG - Web-server MIME type overwrite: mp4=video/mp4
2022-12-31 16:35:18 LOG - Web-server MIME type overwrite: mp3=audio/mpeg
2022-12-31 16:35:18 LOG - Elasticsearch: found 14 of 14 mapped indices. All good.
2022-12-31 16:35:18 LOG - Loading answers from files 'Xtensions/Assistant/answers/answers_*' for 2 languages...
2022-12-31 16:35:19 LOG - Finished loading answers module in 1178 ms.
2022-12-31 16:35:19 LOG - Loading commands from files 'Xtensions/Assistant/commands/teachIt_*' for 2 languages...
2022-12-31 16:35:20 LOG - Finished loading 143(132) predefined commands in 489 ms.
2022-12-31 16:35:20 LOG - Loading commands from files 'Xtensions/Assistant/commands/chats_*' for 2 languages...
2022-12-31 16:35:21 LOG - Finished loading 777(732) predefined chats in 710 ms.
2022-12-31 16:35:21 LOG - Loaded NLU interpretation-chain with 7 steps: [getPersonalCommand, getFixCommandsExactMatch, getChatSmallTalkMatch, getPublicDbSentenceMatch, getKeywordAnalyzerResult, tryPersonalCommandAsFallback, tryChatSmallTalkAsFallback]
2022-12-31 16:35:21 LOG - Running TTS module setup ...
2022-12-31 16:35:22 ERROR - TTS module - MaryTTS server (http://127.0.0.1:59125) did not answer or had no voices installed. Support has been deactivated for now.
2022-12-31 16:35:22 LOG - TTS module - Added 5 'espeak' voices.
2022-12-31 16:35:22 LOG - TTS module - Added 6 'pico' voices.
2022-12-31 16:35:22 LOG - TTS module setup has cleaned up '0' leftover files.
2022-12-31 16:35:22 LOG - TTS module setup successful.
2022-12-31 16:35:22 LOG - Services:News - Loaded 53 outlets with groups for 2 languages from: Xtensions/ServiceProperties/news-outlets.json
2022-12-31 16:35:22 LOG - RssFeedReader - backup restored with 49 feeds. Last modified: 2022.12.31_13:20:12
2022-12-31 16:35:22 LOG - Active workers: 2
2022-12-31 16:35:22 LOG - loading webSocket settings from Xtensions/assist.custom.properties... done.
2022-12-31 16:35:22 LOG - finished loading services mapping for 34 interview modules.
2022-12-31 16:35:22 LOG - Testing services for supported commands...
2022-12-31 16:35:22 LOG - 34 services for 34 commands: All valid!
2022-12-31 16:35:22 LOG - Testing parameters handlers...
2022-12-31 16:35:22 LOG - Parameters:RadioStation - Loaded 92 station arrays with 13 playlists and 7 collections from: Xtensions/ServiceProperties/radio-stations.json
2022-12-31 16:35:22 LOG - ParameterTools - Method 'SmartDevice#deviceNamesScan' has ID: 1
2022-12-31 16:35:22 LOG - 60 parameters: All valid!
2022-12-31 16:35:23 LOG - Server token validated
2022-12-31 16:35:23 LOG - Assistant token validated
2022-12-31 16:35:23 LOG - Added 'admin' and 'assistant' to protected accounts list.
2022-12-31 16:35:23 LOG - Starting Assistant-API server v2.7.0 (custom)
2022-12-31 16:35:23 LOG - date: 31.12.2022 - 15:35:23 - GMT
2022-12-31 16:35:23 LOG - server running on port 20721
2022-12-31 16:35:23 [Thread-3] INFO log - Logging initialized @6928ms to org.eclipse.jetty.util.log.Slf4jLog
2022-12-31 16:35:24 [Thread-3] INFO EmbeddedJettyServer - == Spark has ignited ...
2022-12-31 16:35:24 [Thread-3] INFO EmbeddedJettyServer - >> Listening on 0.0.0.0:20721
2022-12-31 16:35:24 [Thread-3] INFO Server - jetty-9.4.48.v20220622; built: 2022-06-21T20:42:25.880Z; git: 6b67c5719d1f4371b33655ff2d047d24e171e49a; jvm 11.0.16+8-post-Raspbian-1deb11u1
2022-12-31 16:35:24 [Thread-3] INFO session - DefaultSessionIdManager workerName=node0
2022-12-31 16:35:24 [Thread-3] INFO session - No SessionScavenger set, using defaults
2022-12-31 16:35:24 [Thread-3] INFO session - node0 Scavenging every 600000ms
2022-12-31 16:35:24 [Thread-3] INFO AbstractConnector - Started ServerConnector@18558c9{HTTP/1.1, (http/1.1)}{0.0.0.0:20721}
2022-12-31 16:35:24 [Thread-3] INFO Server - Started @7238ms
2022-12-31 16:35:28 LOG - Clients: Checking connection to socket messenger...
2022-12-31 16:35:28 LOG - Clients: Socket messenger found.
2022-12-31 16:35:28 [Thread-2] INFO SocketClientHandler - WEBSOCKET-CLIENT - Connecting to: ws://localhost:20723/messages/
2022-12-31 16:35:29 [WebSocketClient@28706772-31] INFO SepiaSocketClient - WEBSOCKET-CLIENT: Got connection
2022-12-31 16:35:29 [Thread-20] INFO SepiaSocketClient - WEBSOCKET-CLIENT: Authenticating user: 'uid1005'
2022-12-31 16:35:33 LOG - USER uid1003 used SERVICE timer - TS: 1672500933202 - LANGUAGE: de - CLIENT: b1_chrome_browser_v0.25.0 - API: v2.7.0
2022-12-31 16:35:33 LOG - USER uid1003 used SERVICE timer - TS: 1672500933215 - LANGUAGE: de - CLIENT: b1_chrome_browser_v0.25.0 - API: v2.7.0
2022-12-31 16:35:33 LOG - USER uid1003 used SERVICE events_personal - TS: 1672500933170 - LANGUAGE: de - CLIENT: b1_chrome_browser_v0.25.0 - API: v2.7.0
2022-12-31 16:36:08 LOG - USER uid1007 used SERVICE events_personal - TS: 1672500968204 - LANGUAGE: de - CLIENT: b1_chrome_browser_v0.25.0 - API: v2.7.0
2022-12-31 16:36:08 LOG - USER uid1007 used SERVICE timer - TS: 1672500968234 - LANGUAGE: de - CLIENT: b1_chrome_browser_v0.25.0 - API: v2.7.0
2022-12-31 16:36:08 LOG - USER uid1007 used SERVICE timer - TS: 1672500968262 - LANGUAGE: de - CLIENT: b1_chrome_browser_v0.25.0 - API: v2.7.0
2022-12-31 16:36:22 LOG - JSON-Backup-worker: START
2022-12-31 16:36:22 LOG - JSON-Backup-worker: Data has been stored! (1 time(s)) It took (ms): 228, average (ms): 10000
2022-12-31 16:36:33 ERROR - OpenHAB - failed to get devices from server!
2022-12-31 16:37:07 ERROR - OpenHAB - failed to get devices from server!

**Comment by tlrider99** [comment]
curl -H "Authorization: Bearer oh.sepia.slOMPy2LjJwpmmSgDTYtmlnrkamlIpSmzpXrevpkE9nbxo98aYfc2J8Cxoy9Fxxxxxxxxxx"A -X GET http://192.168.10.90:8080/rest/items works fine.
2022-12-31 16:44:40 LOG - User 'uid1003' set new roles for user: uid1007 - Roles: ["user","smarthomeadmin","smarthomeguest","tester","developer"]
2022-12-31 16:45:18 ERROR - OpenHAB - failed to get devices from server!

**Comment by fquirin** [comment]
Hmm, that's weird, there should be a new message right after "failed to get devices..." 🤔. Can you double-check if this is really the new .jar from previous post? Did the file reset for some reason maybe? (Docker container reset, shared folder or something?).

**Comment by tlrider99** [comment]
yes it is.
![image](https://user-images.githubusercontent.com/29237172/210149217-60aa4e6a-7106-495e-840b-d87ca8cd530c.png)
Sepia is running on a Raspberry alone without Docker e.g.

**Comment by fquirin** [comment]
I'll have to test the files again next year (next days ;)) to see if something went wrong during the build :-(

**Comment by tlrider99** [comment]
Then slide well into the new year and have fun. Looking forward to the next tests.

BR
Dirk

**Comment by fquirin** [comment]
New year, new try ^^.

I've created a new JAR, added few more log entries and this time I made sure it is 100% the correct ZIP ^^: 
[sepia-assist-v2.7.0.jar.zip](https://github.com/SEPIA-Framework/sepia-docs/files/10360874/sepia-assist-v2.7.0.jar.zip)

Same procedure as last year ... plz 🤞 🙂 

[EDIT] When I close for example my openHAB server, this is the error I get in the log now:
```
2023-01-06 15:49:10 ERROR - OpenHAB - failed to get devices from server!
JSON response:
{
    "code": -1,
    "error": "java.net.ConnectException: Connection refused: connect",
    "HTTP_REST_SUCCESS": false
}
Checking if 'localhost' machine is reachable...
Is machine reachable? true
Checking if 'http://localhost:8080' host is reachable...
Host check ERROR: 2023-01-06 15:49:10 ERROR - Could not get 'http://localhost:8080', error: Connection refused: connect
```

"Connection refused" indicates an authorization issue, but here it actually means that there is no server at localhost:8080.

**Comment by tlrider99** [comment]
Hi Florian,
Have a healthy and successful 2023.

This will now be written in the log:
JSON response:
{
    "code": -1,
    "error": "java.net.MalformedURLException: no protocol: 192.168.10.90:8080\/rest\/items",
    "HTTP_REST_SUCCESS": false
}
Checking if '192.168.10.90' machine is reachable...
Is machine reachable? true
Checking if '192.168.10.90:8080' host is reachable...
Host check ERROR: 2023-01-07 11:31:00 ERROR - Could not get '192.168.10.90:8080', error: no protocol: 192.168.10.90:8080

Grüße
Dirk

**Comment by fquirin** [comment]
Hi Dirk,

>Have a healthy and successful 2023.

Ty, you too! :-)

>java.net.MalformedURLException: no protocol: 192.168.10.90:8080/rest/items

Please add `http://` to your openHAB host URL 😉. I thought we had double-checked the URL before 🤔 

The missing protocol seems to be a common error now, I guess I have to add some URL validation checks for the next version ^^.

**Comment by tlrider99** [comment]
That was it!

Danke
Dirk
