### ISSUE TITLE
Can not change device type

### ISSUE THREAD

**Issue by eX00r** [SEPIA-Framework/sepia-docs#24]
Hello,

thank you for your wonderful work!

I was able to set up sepia to run along with openhab. I registered sepia within the smarthome tab after saving the openhab IP within the config tab. I am able to load my devices and I can switch them on and off manually BUT unfortunately when I am trying to change the device type or room I get this error, although (as mentioned) I already pressed the 'REGISTER SEPIA' button and it was confirmed by the messagebox:

> Smart home item: zway_zwayDevice_***_***_***_*2_2_switchPowerOutlet_ZWayVDev_zway_*_*_37, FAILED to change 'sepia-type' to: light

I would be very thankful for your advices.

**Comment by sepia-assistant** [comment]
Thank you for the kind words :-)

It seems that your devices are somehow write protected. There might be some additional info in the SEPIA server log (~/SEPIA/sepia-assist-server/log.out) when you try to write the data.

Do you use the Paper UI of openHAB or item files? There is a bit [more info about it ->here<-](https://github.com/SEPIA-Framework/sepia-docs/wiki/Smart-Home-Controls#option-b-if-you-create-items-via-items-file-credits-to-mtothekay).

**Comment by eX00r** [comment]
thanks for the quick response.

I will check the logs later at home.

Regarding your question:
I am using PaperUI.

**Comment by eX00r** [comment]
Seems like the mentioned log does not show anything new. I just hit the button "Register Sepia" and got a message saying:

`{
  "result": "success",
  "msg": "SEPIA Framework was registered successfully inside smart home HUB."
}`

But the log (~/SEPIA/sepia-assist-server/log.out) shows it's newest entry from 3rd of March:

`2020-03-02 00:06:49 LOG - Security policy and manager set.
2020-03-02 00:06:49 LOG - Security sandbox loaded with 6 entries.
2020-03-02 00:06:49 LOG - JAVA_HOME: /***/***/zulu*.*.*.*-ca-jdk1.8.0_222-***/jre
2020-03-02 00:06:49 LOG - loading settings from Xtensions/assist.custom.properties... done.
2020-03-02 00:06:49 LOG - --- Running SEPIA-Assist-API with CUSTOM settings ---
2020-03-02 00:06:50 [main] INFO StaticFilesConfiguration - External StaticResourceHandler configured with folder = Xtensions/WebContent
2020-03-02 00:06:50 LOG - Web-server is active and uses folder: Xtensions/WebContent
2020-03-02 00:06:50 LOG - Web-server MIME type overwrite: mp4=video/mp4
2020-03-02 00:06:50 LOG - Web-server MIME type overwrite: mp3=audio/mpeg
2020-03-02 00:06:50 LOG - Elasticsearch: found 12 of 12 mapped indices. All good.
2020-03-02 00:06:50 LOG - Finished loading answers module in 473 ms.
2020-03-02 00:06:50 LOG - Finished loading 122(111) predefined commands in 71 ms.
2020-03-02 00:06:50 LOG - Finished loading 794(749) predefined chats in 277 ms.
2020-03-02 00:06:51 LOG - Loaded NLU interpretation-chain with 7 steps: [getPersonalCommand, getFixCommandsExactMatch, getChatSmallTalkMatch, getPublicDbSentenceMatch, getKeywordAnalyzerResult, tryPersonalCommandAsFallback, tryChatSmallTalkAsFallback]
2020-03-02 00:06:51 LOG - Running TTS module setup ...
2020-03-02 00:06:51 LOG - TTS module setup has cleaned up '0' leftover files.
2020-03-02 00:06:51 LOG - TTS module setup successful.
2020-03-02 00:06:51 LOG - Services:News - Loaded 34 outlets with groups for 2 languages from: Xtensions/ServiceProperties/news-outlets.json
2020-03-02 00:06:51 LOG - RssFeedReader - backup restored with 34 feeds. Last modified: 2020.03.01_23:58:30
2020-03-02 00:06:51 LOG - Active workers: 2
2020-03-02 00:06:51 LOG - loading webSocket settings from Xtensions/assist.custom.properties... done.
2020-03-02 00:06:51 LOG - finished loading services mapping for 33 interview modules.
2020-03-02 00:06:51 LOG - Testing services for supported commands...
2020-03-02 00:06:51 LOG - 33 services for 33 commands: All valid!
2020-03-02 00:06:51 LOG - Testing parameters handlers...
2020-03-02 00:06:51 LOG - Parameters:RadioStation - Loaded 76 station arrays with 11 playlists and 6 collections from: Xtensions/ServiceProperties/radio-stations.json
2020-03-02 00:06:51 LOG - 58 parameters: All valid!
2020-03-02 00:06:51 LOG - Server token validated
2020-03-02 00:06:51 LOG - Assistant token validated
2020-03-02 00:06:51 LOG - Added 'admin' and 'assistant' to protected accounts list.
2020-03-02 00:06:51 LOG - Starting Assistant-API server v2.4.1 (custom)
2020-03-02 00:06:51 LOG - date: 02.03.2020 - 00:06:51 - GMT
2020-03-02 00:06:51 LOG - server running on port 20721
2020-03-02 00:06:51 [Thread-3] INFO log - Logging initialized @2290ms to org.eclipse.jetty.util.log.Slf4jLog
2020-03-02 00:06:51 [Thread-3] INFO EmbeddedJettyServer - == Spark has ignited ...
2020-03-02 00:06:51 [Thread-3] INFO EmbeddedJettyServer - >> Listening on 0.0.0.0:20721
2020-03-02 00:06:51 [Thread-3] INFO Server - jetty-9.4.18.v20190429; built: 2019-04-29T20:42:08.989Z; git: e1bc35120a6617ee3df052294e433f3a25ce7097; jvm 1.8.0_222-b178
2020-03-02 00:06:52 [Thread-3] INFO session - DefaultSessionIdManager workerName=node0
2020-03-02 00:06:52 [Thread-3] INFO session - No SessionScavenger set, using defaults
2020-03-02 00:06:52 [Thread-3] INFO session - node0 Scavenging every 600000ms
2020-03-02 00:06:52 [Thread-3] ERROR Spark - ignite failed
java.io.IOException: Failed to bind to /0.0.0.0:20721
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:308)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:396)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at spark.embeddedserver.jetty.EmbeddedJettyServer.ignite(EmbeddedJettyServer.java:149)
	at spark.Service.lambda$init$2(Service.java:574)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
	... 9 more`

I have no Idea what to do better.

**Comment by fquirin** [comment]
Thanks for the info. I'll add a note to the wiki docs :-)
